### ISSUE TITLE
Fail to deploy - issue with ruby version

### ISSUE THREAD

**Issue by tman16** [desklabs/canvas-drive#2]
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.3.0
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Your Ruby version is 2.3.0, but your Gemfile specified 2.3.1
       Bundler Output: Your Ruby version is 2.3.0, but your Gemfile specified 2.3.1
 !
 !     Failed to install gems via Bundler.
 !     Detected a mismatch between your Ruby version installed and
 !     Ruby version specified in Gemfile or Gemfile.lock:
 !     https://devcenter.heroku.com/articles/ruby-versions#your-ruby-version-is-x-but-your-gemfile-specified-y
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed

**Comment by kpsf** [comment]
I updated the ruby version and was able to successfully deploy. You should be good to go.
