### ISSUE TITLE
It comes up with professional Dyno after installing the app

### ISSUE THREAD

**Issue by tman16** [desklabs/canvas-drive#3]
Thank you for fixing the ruby version on previous post.

I have now installed the app and was wondering does this mean the integration will cost $25 a month as it looks like a professional dyno is required?

**Comment by kpsf** [comment]
You can scale down the dynos from the resources tab: https://screencast.com/t/gCogTw0MlB

Depending on your usage level, using the free dynos should be ok. If you need more, you can always scale up.
